apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: amb-ambulance-ufe
spec:
  module-uri: http://amb-ambulance-ufe.wac-hospital/build/amb-ufe.esm.js
  # module-uri: http://xbalcercik-ambulance-ufe.wac-hospital/build/reko-ufe.esm.js

                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: amb-ambulance-wl-app    # element, ktorý bude vložený na stránku amb-medical-app or amb-ambulance-wl-app
                                    # pri navigácii na zoznam čakajúcich
      attributes:
      - name: api-base
        value: /amb-api
      - name: ambulance-id
        value: bobulova
      path: amb-ambulance-wl      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny amb-ambulance-wl  or medical
      title: Zoznam čakajúcich amb      # názov mikro aplikácie
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  # hash-suffix: v1alpha1           # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach