apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/amb-ambulance-ufe
- ../../../apps/amb-ambulance-webapi

components:
- ../../../components/version-developers

patches:
- path: patches/ambulance-webapi.service.yaml